name: 'Build / Publish'
on: [push, pull_request]

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 3.1.x
    - uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 5.0.x

    # https://github.com/actions/setup-dotnet/issues/155#issuecomment-748452076
    - run: dotnet nuget locals all --clear    
    - run: dotnet build --configuration Release
    - run: dotnet test --no-build --configuration Release
    - run: dotnet pack --no-build --output . --configuration Release

    - if: github.ref == 'refs/heads/main'
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate 

    - if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v2-preview
      with:
        path: '*.nupkg'